# Generated by Django 3.1.7 on 2021-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200)),
                ('img_caption', models.CharField(max_length=10000)),
                ('username', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
