# Generated by Django 3.1.7 on 2021-04-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_usercomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='img_caption',
        ),
    ]
