# Generated by Django 3.1.7 on 2021-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_usercomments_img_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdayComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('usercomment', models.CharField(max_length=1000)),
            ],
        ),
    ]
